# Comprehensive seed dataset for course recommendation platform

COURSES_DATA = [
    # --- FULL STACK & SOFTWARE DEVELOPMENT ---
    {
        "id": "c-fs-001",
        "title": "Complete Full Stack Web Development",
        "instructor": "Dr. Angela Yu & Brad Traversy",
        "category": "Full Stack Development",
        "department": "CSE",
        "difficulty": "Intermediate",
        "rating": 4.8,
        "students": 45200,
        "duration": "48 hours",
        "price": 49.99,
        "skills": ["HTML5", "CSS3", "JavaScript", "React", "Node.js", "Express", "MongoDB"],
        "technologies": ["React", "Node.js", "Express", "MongoDB", "JavaScript"],
        "tags": ["fullstack", "webdev", "mern", "javascript"],
        "description": "Master frontend and backend web development using the MERN stack. Build production web apps from scratch.",
        "thumbnail": "https://images.unsplash.com/photo-1593720213428-28a5b9e94613?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-fs-003", "c-fs-005", "c-fs-007", "c-fs-008"]
    },
    {
        "id": "c-fs-002",
        "title": "HTML CSS JavaScript Complete Course",
        "instructor": "Jonas Schmedtmann",
        "category": "Frontend Development",
        "department": "CSE",
        "difficulty": "Beginner",
        "rating": 4.7,
        "students": 62100,
        "duration": "32 hours",
        "price": 29.99,
        "skills": ["HTML5", "CSS3", "JavaScript", "DOM Manipulation", "Responsive Design"],
        "technologies": ["HTML", "CSS", "JavaScript"],
        "tags": ["frontend", "web", "beginner"],
        "description": "The foundation course for modern web design. Responsive layouts, ES6+ JavaScript, CSS Grid and Flexbox.",
        "thumbnail": "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-fs-001", "c-fs-003"]
    },
    {
        "id": "c-fs-003",
        "title": "React.js Complete Guide (incl Hooks, React Router, Redux)",
        "instructor": "Maximilian Schwarzmüller",
        "category": "Frontend Development",
        "department": "CSE",
        "difficulty": "Intermediate",
        "rating": 4.9,
        "students": 89000,
        "duration": "50 hours",
        "price": 39.99,
        "skills": ["React", "JSX", "Hooks", "State Management", "Redux Toolkit", "React Router"],
        "technologies": ["React", "JavaScript", "Redux"],
        "tags": ["react", "frontend", "ui", "javascript"],
        "description": "Dive deep into React.js from fundamentals to advanced state management with Redux Toolkit and context API.",
        "thumbnail": "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-fs-004", "c-fs-008", "c-fs-014"]
    },
    {
        "id": "c-fs-004",
        "title": "Advanced React & Next.js Masterclass",
        "instructor": "Dan Abramov & Kent C. Dodds",
        "category": "Frontend Development",
        "department": "CSE",
        "difficulty": "Advanced",
        "rating": 4.9,
        "students": 24500,
        "duration": "28 hours",
        "price": 59.99,
        "skills": ["React Server Components", "Next.js", "TypeScript", "Performance Optimization", "SSR"],
        "technologies": ["React", "Next.js", "TypeScript"],
        "tags": ["react", "nextjs", "advanced", "ssr"],
        "description": "Build high-performance, SEO-optimized web applications with Next.js App Router and Server Components.",
        "thumbnail": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-fs-003", "c-fs-013"]
    },
    {
        "id": "c-fs-005",
        "title": "Node.js Backend Development with Express",
        "instructor": "Andrew Mead",
        "category": "Backend Development",
        "department": "CSE",
        "difficulty": "Intermediate",
        "rating": 4.7,
        "students": 38900,
        "duration": "35 hours",
        "price": 34.99,
        "skills": ["Node.js", "Express.js", "REST API", "JWT Authentication", "Async JavaScript"],
        "technologies": ["Node.js", "Express", "JavaScript"],
        "tags": ["backend", "nodejs", "api", "express"],
        "description": "Build scalable REST APIs, microservices, and web servers with Node.js and Express.",
        "thumbnail": "https://images.unsplash.com/photo-1627398242454-45a1465c2479?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-fs-006", "c-fs-007", "c-fs-008"]
    },
    {
        "id": "c-fs-006",
        "title": "MongoDB for Developers & Database Design",
        "instructor": "MongoDB University",
        "category": "Database",
        "department": "CSE",
        "difficulty": "Intermediate",
        "rating": 4.6,
        "students": 29000,
        "duration": "20 hours",
        "price": 24.99,
        "skills": ["MongoDB", "NoSQL", "Aggregation Framework", "Data Modeling", "Indexing"],
        "technologies": ["MongoDB", "NoSQL"],
        "tags": ["mongodb", "database", "nosql"],
        "description": "Learn document-oriented database modeling, indexing, aggregation pipelines, and production scaling.",
        "thumbnail": "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-fs-005", "c-fs-008"]
    },
    {
        "id": "c-fs-007",
        "title": "REST API Development with Flask & Python",
        "instructor": "Jose Salvatierra",
        "category": "Backend Development",
        "department": "CSE",
        "difficulty": "Intermediate",
        "rating": 4.8,
        "students": 31200,
        "duration": "24 hours",
        "price": 29.99,
        "skills": ["Python", "Flask", "SQLAlchemy", "JWT", "REST API Design"],
        "technologies": ["Python", "Flask", "SQLite", "PostgreSQL"],
        "tags": ["python", "flask", "backend", "api"],
        "description": "Build lightweight, high-speed RESTful Web APIs using Python Flask and SQLAlchemy.",
        "thumbnail": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-dsa-001", "c-fs-010"]
    },
    {
        "id": "c-fs-008",
        "title": "Complete MERN Stack Development (MongoDB, Express, React, Node)",
        "instructor": "Brad Traversy",
        "category": "Full Stack Development",
        "department": "CSE",
        "difficulty": "Intermediate",
        "rating": 4.9,
        "students": 71000,
        "duration": "42 hours",
        "price": 44.99,
        "skills": ["React", "Node.js", "Express", "MongoDB", "Redux", "JWT Auth"],
        "technologies": ["React", "Node.js", "Express", "MongoDB"],
        "tags": ["mern", "fullstack", "react", "nodejs"],
        "description": "Build full stack social networking and eCommerce web applications with the MERN stack.",
        "thumbnail": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-fs-001", "c-fs-003", "c-fs-005"]
    },
    {
        "id": "c-fs-009",
        "title": "Java Spring Boot Full Stack Development",
        "instructor": "In28Minutes Official",
        "category": "Full Stack Development",
        "department": "CSE",
        "difficulty": "Intermediate",
        "rating": 4.7,
        "students": 42300,
        "duration": "40 hours",
        "price": 39.99,
        "skills": ["Java", "Spring Boot", "Spring Data JPA", "Spring Security", "React"],
        "technologies": ["Java", "Spring Boot", "React", "PostgreSQL"],
        "tags": ["java", "springboot", "enterprise", "fullstack"],
        "description": "Build production-grade Java enterprise applications with Spring Boot microservices and React.",
        "thumbnail": "https://images.unsplash.com/photo-1484557985045-edf25e08da73?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-dsa-002", "c-dsa-007"]
    },
    {
        "id": "c-fs-010",
        "title": "Django Full Stack Web Development",
        "instructor": "Nick Walter",
        "category": "Full Stack Development",
        "department": "CSE",
        "difficulty": "Intermediate",
        "rating": 4.7,
        "students": 33100,
        "duration": "30 hours",
        "price": 34.99,
        "skills": ["Python", "Django", "ORM", "Templates", "PostgreSQL"],
        "technologies": ["Python", "Django", "PostgreSQL"],
        "tags": ["python", "django", "fullstack"],
        "description": "Build robust, secure Python web apps with Django ORM, authentication, and admin dashboards.",
        "thumbnail": "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-fs-007", "c-dsa-001"]
    },

    # --- DSA & PROGRAMMING ---
    {
        "id": "c-dsa-001",
        "title": "Python Programming Masterclass & DSA Foundations",
        "instructor": "Tim Buchalka & Jose Portilla",
        "category": "Data Structures & Algorithms",
        "department": "CSE",
        "difficulty": "Beginner",
        "rating": 4.8,
        "students": 112000,
        "duration": "60 hours",
        "price": 29.99,
        "skills": ["Python", "Object-Oriented Programming", "Data Structures", "Algorithms"],
        "technologies": ["Python"],
        "tags": ["python", "dsa", "programming", "beginner"],
        "description": "Learn Python 3 from zero to hero. Covers syntax, OOP, lists, dicts, stacks, queues, and search algorithms.",
        "thumbnail": "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-dsa-004", "c-ai-002"]
    },
    {
        "id": "c-dsa-002",
        "title": "Data Structures & Algorithms in Java Masterclass",
        "instructor": "Abdul Bari",
        "category": "Data Structures & Algorithms",
        "department": "CSE",
        "difficulty": "Intermediate",
        "rating": 4.9,
        "students": 94000,
        "duration": "55 hours",
        "price": 39.99,
        "skills": ["Java", "Arrays", "Linked Lists", "Trees", "Graphs", "Dynamic Programming"],
        "technologies": ["Java"],
        "tags": ["java", "dsa", "algorithms", "problem-solving"],
        "description": "Master fundamental DSA with Java. Visual explanations for recursion, sorting, binary trees, and graph algorithms.",
        "thumbnail": "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-dsa-003", "c-dsa-004", "c-fs-009"]
    },
    {
        "id": "c-dsa-003",
        "title": "Data Structures & Algorithms in C++",
        "instructor": "Abdul Bari & Saurabh Shukla",
        "category": "Data Structures & Algorithms",
        "department": "CSE",
        "difficulty": "Intermediate",
        "rating": 4.9,
        "students": 87000,
        "duration": "52 hours",
        "price": 34.99,
        "skills": ["C++", "Pointers", "Memory Management", "STL", "Trees", "Graphs", "DP"],
        "technologies": ["C++", "STL"],
        "tags": ["cpp", "dsa", "competitive-programming"],
        "description": "High performance computing and algorithmic problem solving using C++ Standard Template Library (STL).",
        "thumbnail": "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-dsa-002", "c-dsa-004", "c-ece-002"]
    },
    {
        "id": "c-dsa-004",
        "title": "Competitive Programming & Advanced Algorithms",
        "instructor": "William Fiset & Errichto",
        "category": "Data Structures & Algorithms",
        "department": "CSE",
        "difficulty": "Advanced",
        "rating": 4.9,
        "students": 31000,
        "duration": "45 hours",
        "price": 49.99,
        "skills": ["Dynamic Programming", "Graph Theory", "Segment Trees", "Fenwick Trees", "Greedy"],
        "technologies": ["C++", "Python", "Algorithms"],
        "tags": ["cp", "leetcode", "advanced-dsa"],
        "description": "Crack technical interviews at FANG and excel in LeetCode/Codeforces with advanced algorithmic techniques.",
        "thumbnail": "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-dsa-003", "c-dsa-001"]
    },

    # --- AI / MACHINE LEARNING / DEEP LEARNING / DATASCIENCE ---
    {
        "id": "c-ai-001",
        "title": "Artificial Intelligence Complete Course: A-Z",
        "instructor": "Hadel de Ponteves & Kirill Eremenko",
        "category": "Artificial Intelligence",
        "department": "AI & DS",
        "difficulty": "Beginner",
        "rating": 4.8,
        "students": 76500,
        "duration": "40 hours",
        "price": 39.99,
        "skills": ["AI Fundamentals", "Q-Learning", "Search Algorithms", "Neural Networks", "Deep Q-Learning"],
        "technologies": ["Python", "PyTorch", "TensorFlow"],
        "tags": ["ai", "machine-learning", "python"],
        "description": "Comprehensive introduction to Artificial Intelligence concepts, game AI, and deep reinforcement learning.",
        "thumbnail": "https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-ai-002", "c-ai-003", "c-genai-001"]
    },
    {
        "id": "c-ai-002",
        "title": "Machine Learning with Python & Scikit-Learn",
        "instructor": "Andrew Ng & Jose Portilla",
        "category": "Machine Learning",
        "department": "AI & ML",
        "difficulty": "Intermediate",
        "rating": 4.9,
        "students": 135000,
        "duration": "44 hours",
        "price": 44.99,
        "skills": ["Supervised Learning", "Regression", "Classification", "Random Forests", "SVM", "Scikit-Learn"],
        "technologies": ["Python", "Scikit-Learn", "Pandas", "NumPy"],
        "tags": ["ml", "machine-learning", "scikit-learn", "python"],
        "description": "Master statistical learning, regression, decision trees, cross-validation, and hyperparameter tuning in Python.",
        "thumbnail": "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-ai-001", "c-ai-003", "c-ai-004"]
    },
    {
        "id": "c-ai-003",
        "title": "Deep Learning Specialization with PyTorch & TensorFlow",
        "instructor": "Andrew Ng & DeepLearning.AI",
        "category": "Deep Learning",
        "department": "AI & ML",
        "difficulty": "Advanced",
        "rating": 4.9,
        "students": 98000,
        "duration": "60 hours",
        "price": 59.99,
        "skills": ["Neural Networks", "CNN", "RNN", "Transformers", "Backpropagation", "PyTorch"],
        "technologies": ["PyTorch", "TensorFlow", "Python"],
        "tags": ["deep-learning", "pytorch", "neural-networks"],
        "description": "Build and train multi-layer perceptrons, convolutional networks (CNNs), and recurrent networks (RNNs) from scratch.",
        "thumbnail": "https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-ai-002", "c-ai-005", "c-ai-006"]
    },
    {
        "id": "c-ai-004",
        "title": "Natural Language Processing (NLP) with Python",
        "instructor": "Lazy Programmer & Dan Jurafsky",
        "category": "NLP",
        "department": "AI & DS",
        "difficulty": "Intermediate",
        "rating": 4.7,
        "students": 41200,
        "duration": "30 hours",
        "price": 39.99,
        "skills": ["Text Processing", "TF-IDF", "Word2Vec", "BERT", "NLTK", "Spacy"],
        "technologies": ["Python", "NLTK", "Transformers", "Spacy"],
        "tags": ["nlp", "text-mining", "bert"],
        "description": "Tokenization, sentiment analysis, named entity recognition, topic modeling, and transformer models for text.",
        "thumbnail": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-ai-003", "c-genai-001", "c-genai-002"]
    },
    {
        "id": "c-ai-005",
        "title": "Computer Vision with Python & OpenCV",
        "instructor": "Adrian Rosebrock",
        "category": "Computer Vision",
        "department": "AI & ML",
        "difficulty": "Intermediate",
        "rating": 4.8,
        "students": 37800,
        "duration": "36 hours",
        "price": 42.99,
        "skills": ["OpenCV", "Image Processing", "YOLO Object Detection", "Face Recognition", "CNN"],
        "technologies": ["Python", "OpenCV", "PyTorch"],
        "tags": ["computer-vision", "opencv", "yolo"],
        "description": "Real-time object detection, face recognition, spatial transformations, and autonomous vision systems.",
        "thumbnail": "https://images.unsplash.com/photo-1591696205602-2f950c417cb9?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-ai-003", "c-mech-011"]
    },
    {
        "id": "c-ai-006",
        "title": "Data Science with Python Masterclass",
        "instructor": "Jose Portilla",
        "category": "Data Science",
        "department": "AI & DS",
        "difficulty": "Beginner",
        "rating": 4.8,
        "students": 105000,
        "duration": "48 hours",
        "price": 34.99,
        "skills": ["Pandas", "NumPy", "Matplotlib", "Seaborn", "Data Cleaning", "EDA"],
        "technologies": ["Python", "Pandas", "NumPy", "Matplotlib"],
        "tags": ["datascience", "pandas", "python"],
        "description": "Data analysis, data visualization, exploratory data analysis, and predictive modeling using Python tools.",
        "thumbnail": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-dsa-001", "c-ai-002"]
    },

    # --- GENERATIVE AI ---
    {
        "id": "c-genai-001",
        "title": "Generative AI Complete Guide: LLMs, RAG & LangChain",
        "instructor": "Dr. Ryan Ahmed & Krish Naik",
        "category": "Generative AI",
        "department": "AI & DS",
        "difficulty": "Intermediate",
        "rating": 4.9,
        "students": 54000,
        "duration": "35 hours",
        "price": 49.99,
        "skills": ["Generative AI", "LLMs", "LangChain", "RAG", "Vector Databases", "Prompt Engineering"],
        "technologies": ["Python", "LangChain", "Hugging Face", "ChromaDB", "LlamaIndex"],
        "tags": ["genai", "llm", "rag", "langchain"],
        "description": "Build Enterprise AI apps with Large Language Models, Retrieval Augmented Generation (RAG), and LangChain.",
        "thumbnail": "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-genai-002", "c-genai-003", "c-genai-004"]
    },
    {
        "id": "c-genai-002",
        "title": "Retrieval Augmented Generation (RAG) & Vector Databases",
        "instructor": "Harrison Chase & James Briggs",
        "category": "Generative AI",
        "department": "AI & ML",
        "difficulty": "Advanced",
        "rating": 4.9,
        "students": 28000,
        "duration": "22 hours",
        "price": 54.99,
        "skills": ["RAG Architecture", "Pinecone", "ChromaDB", "Embeddings", "Semantic Search", "LlamaIndex"],
        "technologies": ["Python", "LangChain", "Pinecone", "OpenAI"],
        "tags": ["rag", "vector-db", "semantic-search"],
        "description": "Connect LLMs to custom private data sources with vector embeddings and hybrid BM25 + dense retrieval.",
        "thumbnail": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-genai-001", "c-genai-003"]
    },
    {
        "id": "c-genai-003",
        "title": "Hugging Face Transformers & Fine-Tuning LLMs",
        "instructor": "Lewis Tunstall & Thomas Wolf",
        "category": "Generative AI",
        "department": "AI & ML",
        "difficulty": "Advanced",
        "rating": 4.8,
        "students": 22400,
        "duration": "30 hours",
        "price": 59.99,
        "skills": ["Hugging Face", "LoRA", "QLoRA", "Fine-Tuning", "Transformer Architecture", "PEFT"],
        "technologies": ["PyTorch", "Hugging Face", "Python"],
        "tags": ["huggingface", "transformers", "lora", "fine-tuning"],
        "description": "Fine-tune open-source Llama, Mistral, and BERT models using PEFT, LoRA, and DeepSpeed quantization.",
        "thumbnail": "https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-genai-001", "c-ai-003"]
    },
    {
        "id": "c-genai-004",
        "title": "Prompt Engineering & Building Autonomous AI Agents",
        "instructor": "Andrew Ng & Isa Fulford",
        "category": "Generative AI",
        "department": "AI & DS",
        "difficulty": "Beginner",
        "rating": 4.8,
        "students": 67000,
        "duration": "18 hours",
        "price": 29.99,
        "skills": ["Prompt Design", "Chain-of-Thought", "AutoGPT", "CrewAI", "Function Calling"],
        "technologies": ["Python", "CrewAI", "OpenAI"],
        "tags": ["prompt-engineering", "agents", "genai"],
        "description": "Master structured prompt techniques, zero/few-shot reasoning, system prompts, and multi-agent workflows.",
        "thumbnail": "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-genai-001", "c-ai-001"]
    },

    # --- CLOUD / DEVOPS / CYBERSECURITY ---
    {
        "id": "c-cloud-001",
        "title": "AWS Certified Solutions Architect Associate",
        "instructor": "Stephane Maarek",
        "category": "Cloud Computing",
        "department": "CSE",
        "difficulty": "Intermediate",
        "rating": 4.9,
        "students": 115000,
        "duration": "45 hours",
        "price": 44.99,
        "skills": ["AWS EC2", "S3", "VPC", "IAM", "Lambda", "CloudFront", "RDS"],
        "technologies": ["AWS", "Cloud"],
        "tags": ["aws", "cloud", "devops", "certification"],
        "description": "Design secure, fault-tolerant, scalable cloud infrastructure on Amazon Web Services.",
        "thumbnail": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-cloud-002", "c-cloud-003"]
    },
    {
        "id": "c-cloud-002",
        "title": "Docker & Kubernetes Complete DevOps Bootcamp",
        "instructor": "Stephen Grider",
        "category": "DevOps",
        "department": "CSE",
        "difficulty": "Intermediate",
        "rating": 4.8,
        "students": 82000,
        "duration": "38 hours",
        "price": 39.99,
        "skills": ["Docker Containers", "Kubernetes Pods", "Helm", "CI/CD", "Container Orchestration"],
        "technologies": ["Docker", "Kubernetes", "Linux"],
        "tags": ["docker", "k8s", "devops", "containers"],
        "description": "Containerize microservices with Docker Compose and orchestrate clusters with Kubernetes.",
        "thumbnail": "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-cloud-001", "c-cloud-003"]
    },
    {
        "id": "c-cloud-003",
        "title": "DevOps Complete Course: Jenkins, Terraform & GitHub Actions",
        "instructor": "Mumshad Mannambeth",
        "category": "DevOps",
        "department": "CSE",
        "difficulty": "Advanced",
        "rating": 4.9,
        "students": 49000,
        "duration": "40 hours",
        "price": 49.99,
        "skills": ["Terraform", "Jenkins", "GitHub Actions", "Ansible", "Linux", "CI/CD Pipelines"],
        "technologies": ["Terraform", "Jenkins", "GitHub Actions", "Docker"],
        "tags": ["devops", "terraform", "cicd", "automation"],
        "description": "Automate infrastructure deployment with Infrastructure as Code (IaC) and CI/CD automation pipelines.",
        "thumbnail": "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-cloud-001", "c-cloud-002"]
    },
    {
        "id": "c-sec-001",
        "title": "Cyber Security Fundamentals & Network Security",
        "instructor": "Nathan House",
        "category": "Cyber Security",
        "department": "CSE",
        "difficulty": "Beginner",
        "rating": 4.7,
        "students": 64000,
        "duration": "26 hours",
        "price": 29.99,
        "skills": ["Network Security", "Firewalls", "Wireshark", "Encryption", "Threat Analysis"],
        "technologies": ["Wireshark", "Linux", "Network Protocols"],
        "tags": ["cybersecurity", "security", "networking"],
        "description": "Foundations of cybersecurity, threat landscapes, network sniffing with Wireshark, and defensive hardening.",
        "thumbnail": "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-sec-002", "c-sec-003"]
    },
    {
        "id": "c-sec-002",
        "title": "Ethical Hacking & Web Application Penetration Testing",
        "instructor": "Zaid Sabih",
        "category": "Cyber Security",
        "department": "CSE",
        "difficulty": "Intermediate",
        "rating": 4.8,
        "students": 85000,
        "duration": "42 hours",
        "price": 44.99,
        "skills": ["Kali Linux", "Metasploit", "Burp Suite", "SQL Injection", "XSS", "Penetration Testing"],
        "technologies": ["Kali Linux", "Burp Suite", "Metasploit"],
        "tags": ["ethical-hacking", "pentesting", "cybersecurity"],
        "description": "Learn ethical hacking hands-on. Discover website vulnerabilities, exploit systems safely, and secure APIs.",
        "thumbnail": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-sec-001", "c-sec-003"]
    },

    # --- MECHANICAL ENGINEERING ---
    {
        "id": "c-mech-001",
        "title": "Python for Mechanical Engineers: Thermodynamics & Fluid Solvers",
        "instructor": "Dr. Rajesh Kumar",
        "category": "Mechanical Engineering",
        "department": "Mechanical",
        "difficulty": "Intermediate",
        "rating": 4.8,
        "students": 18500,
        "duration": "25 hours",
        "price": 34.99,
        "skills": ["Python", "SymPy", "SciPy", "Thermodynamic Modeling", "Fluid Dynamics Solvers"],
        "technologies": ["Python", "SciPy", "Matplotlib"],
        "tags": ["mechanical", "python", "thermodynamics", "simulation"],
        "description": "Apply Python for numerical computation in mechanical engineering: thermodynamics, heat transfer equations, and fluid dynamics.",
        "thumbnail": "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-mech-002", "c-mech-003", "c-mech-007"]
    },
    {
        "id": "c-mech-002",
        "title": "SOLIDWORKS Mechanical Design & Assemblies Masterclass",
        "instructor": "Johan Thorne",
        "category": "CAD/BIM",
        "department": "Mechanical",
        "difficulty": "Beginner",
        "rating": 4.9,
        "students": 52000,
        "duration": "36 hours",
        "price": 39.99,
        "skills": ["3D CAD Modeling", "Assembly Design", "Sheet Metal", "Technical Drawings", "SOLIDWORKS"],
        "technologies": ["SOLIDWORKS", "CAD"],
        "tags": ["solidworks", "cad", "mechanical-design", "3d-modeling"],
        "description": "Master industrial 3D CAD modeling, component assemblies, motion simulation, and drafting with SOLIDWORKS.",
        "thumbnail": "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-mech-003", "c-mech-005", "c-mech-006"]
    },
    {
        "id": "c-mech-003",
        "title": "Ansys Workbench: Easy Steps to Finite Element Analysis (FEA)",
        "instructor": "Dr. Alexander Miller",
        "category": "Mechanical Engineering",
        "department": "Mechanical",
        "difficulty": "Intermediate",
        "rating": 4.8,
        "students": 31000,
        "duration": "28 hours",
        "price": 44.99,
        "skills": ["ANSYS Workbench", "Structural Analysis", "Meshing", "Stress Analysis", "Thermal FEA"],
        "technologies": ["ANSYS", "FEA"],
        "tags": ["ansys", "fea", "structural-simulation", "mechanical"],
        "description": "Simulate stress distribution, modal response, static structural load, and thermal strain using ANSYS FEA.",
        "thumbnail": "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-mech-002", "c-mech-008"]
    },
    {
        "id": "c-mech-004",
        "title": "The Complete Mechanical Engineering Advanced Diploma",
        "instructor": "Prof. Michael Schmidt",
        "category": "Mechanical Engineering",
        "department": "Mechanical",
        "difficulty": "Advanced",
        "rating": 4.7,
        "students": 24000,
        "duration": "65 hours",
        "price": 54.99,
        "skills": ["Thermodynamics", "Fluid Mechanics", "Strength of Materials", "Kinematics of Machines", "Machine Design"],
        "technologies": ["Mechanical Design", "GATE Prep"],
        "tags": ["mechanical", "theory", "engineering-fundamentals"],
        "description": "Comprehensive academic theory masterclass covering machine design, thermodynamics, fluid dynamics, and mechanics.",
        "thumbnail": "https://images.unsplash.com/photo-1537462715879-360eeb61a0ad?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-mech-001", "c-mech-003"]
    },
    {
        "id": "c-mech-005",
        "title": "AutoCAD for Mechanical Engineers & Drafting",
        "instructor": "Awais Jamil",
        "category": "CAD/BIM",
        "department": "Mechanical",
        "difficulty": "Beginner",
        "rating": 4.6,
        "students": 41000,
        "duration": "22 hours",
        "price": 24.99,
        "skills": ["2D Drafting", "Geometric Tolerancing", "Isometric Drawing", "AutoCAD Mechanical"],
        "technologies": ["AutoCAD"],
        "tags": ["autocad", "cad", "drafting", "mechanical"],
        "description": "Produce production-ready 2D mechanical engineering blueprints and CAD drawings with AutoCAD.",
        "thumbnail": "https://images.unsplash.com/photo-1572021335469-31706a17aaef?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-mech-002", "c-civ-005"]
    },
    {
        "id": "c-mech-006",
        "title": "CATIA V5 Complete Part Design & Surface Modeling",
        "instructor": "Venkatesh S",
        "category": "CAD/BIM",
        "department": "Mechanical",
        "difficulty": "Intermediate",
        "rating": 4.7,
        "students": 19000,
        "duration": "30 hours",
        "price": 39.99,
        "skills": ["CATIA V5", "Generative Shape Design", "Aerospace Design", "Automotive CAD"],
        "technologies": ["CATIA"],
        "tags": ["catia", "automotive", "aerospace", "cad"],
        "description": "Advanced surfacing, automotive chassis modeling, and aerospace panel design with CATIA V5.",
        "thumbnail": "https://images.unsplash.com/photo-1533749047139-189de3cf06d3?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-mech-002", "c-mech-007"]
    },
    {
        "id": "c-mech-007",
        "title": "Computational Fluid Dynamics (CFD) Fundamentals",
        "instructor": "Dr. Aidan O'Connor",
        "category": "Mechanical Engineering",
        "department": "Mechanical",
        "difficulty": "Advanced",
        "rating": 4.8,
        "students": 16000,
        "duration": "32 hours",
        "price": 49.99,
        "skills": ["ANSYS Fluent", "Navier-Stokes Solvers", "Turbulence Modeling", "Aerodynamics"],
        "technologies": ["ANSYS Fluent", "OpenFOAM"],
        "tags": ["cfd", "ansys-fluent", "aerodynamics", "fluid-mechanics"],
        "description": "Simulate fluid flow, internal heat dissipation, and aerodynamic drag forces using ANSYS Fluent and OpenFOAM.",
        "thumbnail": "https://images.unsplash.com/photo-1628258334105-2a0b3d6efee1?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-mech-001", "c-mech-003"]
    },

    # --- EEE (ELECTRICAL & ELECTRONICS ENGINEERING) ---
    {
        "id": "c-eee-001",
        "title": "MATLAB/Simulink for Power Electronics Engineers",
        "instructor": "Dr. Stephen Patel",
        "category": "EEE",
        "department": "EEE",
        "difficulty": "Intermediate",
        "rating": 4.8,
        "students": 26000,
        "duration": "30 hours",
        "price": 39.99,
        "skills": ["MATLAB", "Simulink", "Inverters", "PWM Controls", "Grid Simulation", "DC-DC Converters"],
        "technologies": ["MATLAB", "Simulink"],
        "tags": ["matlab", "power-electronics", "simulink", "eee"],
        "description": "Model solar inverters, motor drives, buck-boost converters, and microgrid power systems in MATLAB Simulink.",
        "thumbnail": "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-eee-002", "c-eee-003", "c-eee-004"]
    },
    {
        "id": "c-eee-002",
        "title": "Electrical Control & Automation with PLC / SCADA",
        "instructor": "Markus Weber",
        "category": "Automation",
        "department": "EEE",
        "difficulty": "Intermediate",
        "rating": 4.9,
        "students": 38000,
        "duration": "35 hours",
        "price": 44.99,
        "skills": ["PLC Programming", "Ladder Logic", "SCADA HMI", "Siemens TIA Portal", "Industrial Automation"],
        "technologies": ["Siemens S7-1200", "SCADA", "PLC"],
        "tags": ["plc", "scada", "automation", "industrial"],
        "description": "Program industrial Siemens PLCs using Ladder Logic and connect live SCADA supervisory control interfaces.",
        "thumbnail": "https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-eee-001", "c-ece-003", "c-rob-001"]
    },
    {
        "id": "c-eee-003",
        "title": "ETAP Electrical Power System Software Training",
        "instructor": "Eng. Faisal Ahmed",
        "category": "EEE",
        "department": "EEE",
        "difficulty": "Advanced",
        "rating": 4.7,
        "students": 14200,
        "duration": "24 hours",
        "price": 49.99,
        "skills": ["ETAP", "Load Flow Analysis", "Short Circuit Calculation", "Relay Coordination", "Substation Design"],
        "technologies": ["ETAP", "Power Systems"],
        "tags": ["etap", "power-systems", "electrical"],
        "description": "Perform power grid load flow calculations, fault analysis, and protection relay coordination using ETAP.",
        "thumbnail": "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-eee-001", "c-eee-004"]
    },
    {
        "id": "c-eee-004",
        "title": "Solar Energy & Photovoltaic (PV) System Design",
        "instructor": "Dr. Elena Rostova",
        "category": "Renewable Energy",
        "department": "EEE",
        "difficulty": "Beginner",
        "rating": 4.8,
        "students": 32000,
        "duration": "20 hours",
        "price": 29.99,
        "skills": ["PVSyst", "Solar PV Sizing", "MPPT Trackers", "Battery Bank Storage", "Grid-Tied Solar"],
        "technologies": ["PVSyst", "Solar PV"],
        "tags": ["solar", "renewable-energy", "pv-design"],
        "description": "Design commercial and residential rooftop solar energy plants with battery storage and inverter sizing.",
        "thumbnail": "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-eee-001", "c-eee-005"]
    },
    {
        "id": "c-eee-005",
        "title": "Electric Vehicle Technology & Battery Management Systems (BMS)",
        "instructor": "Dr. Vivek Sharma",
        "category": "EEE",
        "department": "EEE",
        "difficulty": "Intermediate",
        "rating": 4.9,
        "students": 29500,
        "duration": "28 hours",
        "price": 44.99,
        "skills": ["Li-Ion Battery Modeling", "BMS Algorithms", "EV Motor Drives", "Regenerative Braking"],
        "technologies": ["MATLAB", "Simulink", "EV Tech"],
        "tags": ["ev", "battery-bms", "electric-vehicles"],
        "description": "Understand electric drivetrain architectures, lithium battery SOC estimation, and BMS circuit controls.",
        "thumbnail": "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-eee-001", "c-eee-004"]
    },

    # --- ECE (ELECTRONICS & COMMUNICATION ENGINEERING) ---
    {
        "id": "c-ece-001",
        "title": "Complete Digital VLSI Design & Cadence Synthesis",
        "instructor": "Dr. Sanjay Vidya",
        "category": "VLSI",
        "department": "ECE",
        "difficulty": "Advanced",
        "rating": 4.9,
        "students": 21000,
        "duration": "45 hours",
        "price": 54.99,
        "skills": ["CMOS Logic", "RTL Synthesis", "Timing Closure", "Static Timing Analysis (STA)", "VLSI Layout"],
        "technologies": ["Cadence Innovus", "Synopsys Design Compiler"],
        "tags": ["vlsi", "semiconductor", "chip-design", "ece"],
        "description": "End-to-end digital VLSI chip design flow from RTL verilog code to floorplanning, placement, and routing.",
        "thumbnail": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-ece-002", "c-ece-006"]
    },
    {
        "id": "c-ece-002",
        "title": "Verilog HDL: Practical ASIC & FPGA Design",
        "instructor": "Kiran Kumar",
        "category": "VLSI",
        "department": "ECE",
        "difficulty": "Intermediate",
        "rating": 4.8,
        "students": 34000,
        "duration": "30 hours",
        "price": 39.99,
        "skills": ["Verilog HDL", "Testbench Design", "Finite State Machines", "Xilinx Vivado", "FPGA"],
        "technologies": ["Verilog", "Xilinx Vivado", "FPGA"],
        "tags": ["verilog", "fpga", "asic", "hdl"],
        "description": "Write synthesisable Verilog HDL code, simulate digital logic testbenches, and deploy to Xilinx FPGAs.",
        "thumbnail": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-ece-001", "c-dsa-003"]
    },
    {
        "id": "c-ece-003",
        "title": "Mastering Microcontrollers with Embedded C",
        "instructor": "Kiran Nayak",
        "category": "Embedded Systems",
        "department": "ECE",
        "difficulty": "Intermediate",
        "rating": 4.9,
        "students": 58000,
        "duration": "40 hours",
        "price": 39.99,
        "skills": ["Embedded C", "ARM Cortex-M", "GPIO", "Timers", "UART", "SPI", "I2C", "STM32"],
        "technologies": ["Embedded C", "STM32", "ARM"],
        "tags": ["embedded", "microcontroller", "arm", "stm32"],
        "description": "Program ARM Cortex-M microcontrollers bare-metal using C language registers, interrupts, and serial protocols.",
        "thumbnail": "https://images.unsplash.com/photo-1601524909162-ae8725290836?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-ece-004", "c-ece-005", "c-eee-002"]
    },
    {
        "id": "c-ece-004",
        "title": "Digital Signal Processing (DSP) From Ground Up in Python",
        "instructor": "Israel Gbati",
        "category": "ECE",
        "department": "ECE",
        "difficulty": "Intermediate",
        "rating": 4.7,
        "students": 23000,
        "duration": "28 hours",
        "price": 34.99,
        "skills": ["Fourier Transform (FFT)", "Convolution", "IIR/FIR Filters", "Audio Signal Processing"],
        "technologies": ["Python", "SciPy", "NumPy"],
        "tags": ["dsp", "signal-processing", "python", "fft"],
        "description": "Implement discrete Fourier transforms, digital FIR/IIR filter design, and spectral audio processing in Python.",
        "thumbnail": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-ece-003", "c-dsa-001"]
    },
    {
        "id": "c-ece-005",
        "title": "Internet of Things (IoT) with ESP32 & Arduino",
        "instructor": "Badr Youssef",
        "category": "IoT",
        "department": "ECE",
        "difficulty": "Beginner",
        "rating": 4.8,
        "students": 47000,
        "duration": "25 hours",
        "price": 29.99,
        "skills": ["ESP32", "MQTT Protocol", "Sensors Interfacing", "Wi-Fi Communication", "ThingSpeak"],
        "technologies": ["ESP32", "Arduino C++", "MQTT"],
        "tags": ["iot", "esp32", "arduino", "sensors"],
        "description": "Build connected smart sensor nodes, send telemetry over MQTT to cloud dashboards using ESP32 Wi-Fi module.",
        "thumbnail": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-ece-003", "c-rob-001"]
    },

    # --- CIVIL ENGINEERING ---
    {
        "id": "c-civ-001",
        "title": "Autodesk Revit Architecture Masterclass: BIM Guide",
        "instructor": "Tayo Dain",
        "category": "CAD/BIM",
        "department": "Civil",
        "difficulty": "Beginner",
        "rating": 4.8,
        "students": 41000,
        "duration": "35 hours",
        "price": 39.99,
        "skills": ["Building Information Modeling (BIM)", "Revit 3D", "Floor Plans", "Schedules", "Rendering"],
        "technologies": ["Autodesk Revit", "BIM"],
        "tags": ["revit", "bim", "civil", "architecture"],
        "description": "Construct parametric 3D building models, architectural plans, elevation views, and quantity takeoffs in Revit.",
        "thumbnail": "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-civ-002", "c-civ-004", "c-civ-005"]
    },
    {
        "id": "c-civ-002",
        "title": "STAAD Pro V8i for Civil Engineers: Structural Analysis",
        "instructor": "Eng. Civil Tutor",
        "category": "Civil Engineering",
        "department": "Civil",
        "difficulty": "Intermediate",
        "rating": 4.7,
        "students": 28000,
        "duration": "26 hours",
        "price": 34.99,
        "skills": ["Structural Analysis", "RCC Design", "Steel Frame Modeling", "Wind & Seismic Loads"],
        "technologies": ["STAAD Pro"],
        "tags": ["staadpro", "structural-analysis", "civil"],
        "description": "Analyze concrete and multi-story steel frame structures against dead, live, wind, and seismic earthquake loads.",
        "thumbnail": "https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-civ-001", "c-civ-003"]
    },
    {
        "id": "c-civ-003",
        "title": "Introduction to GIS & QGIS for Civil & Environmental Engineers",
        "instructor": "Dr. Sarah Jenkins",
        "category": "Civil Engineering",
        "department": "Civil",
        "difficulty": "Beginner",
        "rating": 4.7,
        "students": 22000,
        "duration": "20 hours",
        "price": 27.99,
        "skills": ["QGIS", "Geospatial Analysis", "Coordinate Systems", "Land Survey Mapping", "Hydrology Mapping"],
        "technologies": ["QGIS", "ArcGIS"],
        "tags": ["gis", "qgis", "geospatial", "surveying"],
        "description": "Work with spatial data, satellite elevation models, digital elevation maps (DEM), and land contours using open-source QGIS.",
        "thumbnail": "https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-civ-002", "c-civ-004"]
    },
    {
        "id": "c-civ-004",
        "title": "Project Management with Primavera P6 for Construction",
        "instructor": "Planning Engineer Academy",
        "category": "Civil Engineering",
        "department": "Civil",
        "difficulty": "Intermediate",
        "rating": 4.8,
        "students": 31000,
        "duration": "28 hours",
        "price": 42.99,
        "skills": ["Primavera P6", "Critical Path Method (CPM)", "Gantt Charts", "Cost Budgeting", "Earned Value Management"],
        "technologies": ["Primavera P6"],
        "tags": ["primavera", "project-management", "construction"],
        "description": "Manage multi-million dollar construction schedules, resource allocations, S-curves, and delay analysis with Primavera P6.",
        "thumbnail": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-civ-001", "c-civ-005"]
    },
    {
        "id": "c-civ-005",
        "title": "AutoCAD for Civil Engineers & Highway Design",
        "instructor": "Civil Design Hub",
        "category": "CAD/BIM",
        "department": "Civil",
        "difficulty": "Beginner",
        "rating": 4.6,
        "students": 36000,
        "duration": "24 hours",
        "price": 24.99,
        "skills": ["AutoCAD 2D", "Site Layouts", "Road Cross Sections", "Land Survey Blueprinting"],
        "technologies": ["AutoCAD Civil 3D"],
        "tags": ["autocad", "civil-design", "highways"],
        "description": "Draft 2D architectural site plans, highway alignments, and storm drainage layouts using AutoCAD Civil.",
        "thumbnail": "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-civ-001", "c-mech-005"]
    },

    # --- ROBOTICS / AUTOMATION / MECHATRONICS ---
    {
        "id": "c-rob-001",
        "title": "ROS2 Robotics Developer Course: Python & C++",
        "instructor": "Anis Koubaa",
        "category": "Robotics",
        "department": "Mechatronics",
        "difficulty": "Intermediate",
        "rating": 4.9,
        "students": 19500,
        "duration": "38 hours",
        "price": 49.99,
        "skills": ["ROS2", "Robotics Navigation (Nav2)", "Gazebo Simulation", "URDF Models", "SLAM"],
        "technologies": ["ROS2", "Python", "C++", "Gazebo"],
        "tags": ["ros2", "robotics", "slam", "simulation"],
        "description": "Develop autonomous robot software with ROS2 Galactic/Humble, Gazebo physics simulation, and SLAM mapping.",
        "thumbnail": "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=600&q=80",
        "related_ids": ["c-ece-003", "c-eee-002", "c-ai-005"]
    }
]

# Seed demo users for test environments
DEMO_USERS = [
    {
        "id": "u-demo-cse",
        "name": "Alex Chen",
        "email": "alex.cse@example.com",
        "password": "password123",
        "department": "CSE",
        "experience": "Intermediate",
        "skills": ["Python", "JavaScript", "HTML5"],
        "interests": ["React", "Node.js", "AI"]
    },
    {
        "id": "u-demo-ece",
        "name": "Priya Sharma",
        "email": "priya.ece@example.com",
        "password": "password123",
        "department": "ECE",
        "experience": "Beginner",
        "skills": ["C", "Digital Electronics"],
        "interests": ["Embedded Systems", "Microcontrollers", "VLSI"]
    },
    {
        "id": "u-demo-mech",
        "name": "David Miller",
        "email": "david.mech@example.com",
        "password": "password123",
        "department": "Mechanical",
        "experience": "Intermediate",
        "skills": ["3D CAD Modeling", "SOLIDWORKS"],
        "interests": ["ANSYS Workbench", "FEA", "Thermodynamic Modeling"]
    },
    {
        "id": "u-demo-eee",
        "name": "Rohan Gupta",
        "email": "rohan.eee@example.com",
        "password": "password123",
        "department": "EEE",
        "experience": "Intermediate",
        "skills": ["MATLAB", "Electrical Machines"],
        "interests": ["Simulink", "Power Electronics", "Solar PV Sizing"]
    },
    {
        "id": "u-demo-civil",
        "name": "Emily Carter",
        "email": "emily.civil@example.com",
        "password": "password123",
        "department": "Civil",
        "experience": "Beginner",
        "skills": ["AutoCAD 2D"],
        "interests": ["Building Information Modeling (BIM)", "Autodesk Revit", "STAAD Pro"]
    }
]
